In [2]:
import numpy as np

In [ ]:
Task 1

In [11]:
Z = np.diag(np.arange(1, 5), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Task 2

In [45]:
Z = np.random.random((2,10,3))
b = np.argmin(np.absolute(Z - 0.5), axis = 2)
print(Z[0][i][b[i]])
print(Z[1][i][b[i]])
print(Z)

[0.48553998 0.30963637 0.76709634 0.76709634 0.76709634 0.30963637
 0.48553998 0.76709634 0.76709634 0.76709634]
[0.32847798 0.71186282 0.60584671 0.60584671 0.60584671 0.71186282
 0.32847798 0.60584671 0.60584671 0.60584671]
[[[0.48553998 0.30963637 0.76709634]
  [0.26566734 0.60241421 0.39278231]
  [0.02137063 0.41521531 0.55579928]
  [0.28476867 0.89811842 0.69614619]
  [0.10602001 0.55872923 0.54820205]
  [0.32315328 0.40138245 0.70268753]
  [0.34461991 0.99245617 0.84703941]
  [0.58736051 0.03060162 0.55739534]
  [0.7712796  0.93775791 0.40105402]
  [0.91755127 0.06010292 0.48158184]]

 [[0.32847798 0.71186282 0.60584671]
  [0.6451399  0.86966182 0.85188385]
  [0.54518247 0.45309374 0.38021212]
  [0.87295115 0.0913179  0.06330899]
  [0.52391843 0.48155874 0.33962928]
  [0.12785476 0.61124407 0.55339594]
  [0.62468256 0.80782158 0.13625968]
  [0.04016238 0.97814309 0.78772267]
  [0.53377502 0.79350448 0.88793419]
  [0.56629147 0.09757742 0.03894568]]]


In [ ]:
Task 3

In [88]:
Z = np.random.random((6,6))
b = np.amin(Z, axis = 0)
for i in range(6):
    print(a[i].sum()/b[i])

32.040319574477564
1054.3214775013776
198.8166946576951


<class 'IndexError'>: index 3 is out of bounds for axis 0 with size 3

In [ ]:
Task 4

In [111]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max(filter(lambda a: (a[1] and not a[0]), zip(x, x[1:])), key=lambda a: a[1])[1]

5

In [ ]:
Task 5

In [113]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for k in i:
    x[k] += 1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [ ]:
Task 6

In [129]:
Z = np.random.uniform(-60, 60, 10)
print(Z)
print(np.round(Z))
print(np.around(Z))

[-18.43675886 -31.28542337  43.63741449 -55.05061399  47.28653226
   1.57780097 -51.9692228   53.04349003   0.40261586  17.68194068]
[-18. -31.  44. -55.  47.   2. -52.  53.   0.  18.]
[-18. -31.  44. -55.  47.   2. -52.  53.   0.  18.]


In [ ]:
Task 7

In [ ]:
Пока не сделано